name: Deploy to Raspberry Pi

# mainブランチにプッシュされた時に実行
on:
  push:
    branches:
      - main

jobs:
  deploy:
    # 仮想サーバー(Ubuntu)で実行
    runs-on: ubuntu-latest
    
    steps:
      - name: SSH into Raspberry Pi and deploy
        # SSH接続とコマンド実行を自動化するアクション
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          # 以下のスクリプトをラズパイ上で実行
          script: |
            cd ~/wms_svelte
            git pull origin main
            source /home/nh007462/.nvm/nvm.sh
            npm install
            npm run build
            sudo systemctl restart wms-svelte.service